version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      # context: packages/landingpage
      dockerfile: Dockerfile
    volumes:
      # - ./packages/landingpage:/usr/src/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env